lb-proxy:
  port: 8443
  remote-server-info-list:
    - host: 127.0.0.1
      port: 2080
      hostMatcher:
        - SUBNET_MATCH
      matchData: 10.42.0.0/16
    - host: 127.0.0.1
      port: 2080
      hostMatcher:
        - SUBNET_MATCH
      matchData: 10.43.0.0/16
    - host: 127.0.0.1
      port: 2080
      hostMatcher:
        - REGEX_MATCH
      matchData: ".*svc.cluster.local"
  default-remote-server:
    host: 127.0.0.1
    host-matcher: regex_match
    port: 10808
